# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

centraliseCoordinates <- function(x) {
    .Call(`_fieldcoordinate_centraliseCoordinates`, x)
}

writeToPointCloud <- function(x, filename) {
    .Call(`_fieldcoordinate_writeToPointCloud`, x, filename)
}

